name: Multi-Architecture Build

on:
  release:
    types: [published]

jobs:
  build-anycpu:
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: anycpu

    - name: Restore NuGet packages
      run: nuget restore HideOrShowTaskbar.sln  # 替换为您的解决方案文件名

    - name: Build project
      run: |
        msbuild /p:Configuration=Release /p:Platform=anycpu HideOrShowTaskbar.csproj

    - name: Create artifacts directory
      run: mkdir artifacts-anycpu

    - name: Copy EXE to artifacts directory
      run: |
        Copy-Item -Path "bin\Release\HideOrShowTaskbar.exe" -Destination "artifacts-anycpu"

    - run: cd "artifacts-anycpu"

    - run: Rename-Item -Path HideOrShowTaskbar.exe -NewName HideOrShowTaskbar-anycpu.exe -Force

    - run: gh release upload 1.0.0 HideOrShowTaskbar-anycpu.exe --repo $GITHUB_REPOSITORY

  build-x64:
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: x64

    - name: Restore NuGet packages
      run: nuget restore HideOrShowTaskbar.sln  # 替换为您的解决方案文件名

    - name: Build project
      run: |
        msbuild /p:Configuration=Release /p:Platform=x64 HideOrShowTaskbar.csproj

    - name: Create artifacts directory
      run: mkdir artifacts-x64

    - name: Copy EXE to artifacts directory
      run: |
        Copy-Item -Path "bin\x64\Release\HideOrShowTaskbar.exe" -Destination "artifacts-x64"

    - run: cd "artifacts-x64"

    - run: Rename-Item -Path HideOrShowTaskbar.exe -NewName HideOrShowTaskbar-x64.exe -Force

    - run: gh release upload 1.0.0 HideOrShowTaskbar-x64.exe --repo $GITHUB_REPOSITORY
  build-x86:
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: x86

    - name: Restore NuGet packages
      run: nuget restore HideOrShowTaskbar.sln  # 替换为您的解决方案文件名

    - name: Build project
      run: |
        msbuild /p:Configuration=Release /p:Platform=x86 HideOrShowTaskbar.csproj

    - name: Create artifacts directory
      run: mkdir artifacts-x86

    - name: Copy EXE to artifacts directory
      run: |
        Copy-Item -Path "bin\x86\Release\HideOrShowTaskbar.exe" -Destination "artifacts-x86"

    - run: cd "artifacts-x86"

    - run: Rename-Item -Path HideOrShowTaskbar.exe -NewName HideOrShowTaskbar-x86.exe -Force

    - run: gh release upload 1.0.0 HideOrShowTaskbar-x86.exe --repo $GITHUB_REPOSITORY
  build-arm64:
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: arm64

    - name: Restore NuGet packages
      run: nuget restore HideOrShowTaskbar.sln  # 替换为您的解决方案文件名

    - name: Build project
      run: |
        msbuild /p:Configuration=Release /p:Platform=arm64 HideOrShowTaskbar.csproj

    - name: Create artifacts directory
      run: mkdir artifacts-arm64

    - name: Copy EXE to artifacts directory
      run: |
        Copy-Item -Path "bin\arm64\Release\HideOrShowTaskbar.exe" -Destination "artifacts-arm64"

    - run: cd "artifacts-arm64"

    - run: Rename-Item -Path HideOrShowTaskbar.exe -NewName HideOrShowTaskbar-arm64.exe -Force

    - run: gh release upload 1.0.0 HideOrShowTaskbar-arm64.exe --repo $GITHUB_REPOSITORY
