name: Multi-Architecture Build

on:
  release:
    types: [published]

jobs:
  build-anycpu:
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: anycpu

    - name: Restore NuGet packages
      run: nuget restore HideOrShowTaskbar.sln  # 替换为您的解决方案文件名

    - name: Build project
      run: |
        msbuild /p:Configuration=Release /p:Platform=anycpu HideOrShowTaskbar.csproj

    - name: Create artifacts directory
      run: mkdir artifacts-anycpu

    - run: Rename-Item -Path "bin\Release\HideOrShowTaskbar.exe" -NewName "HideOrShowTaskbar-anycpu.exe" -Force

    - run: cd "bin\Release"; gh release upload 1.1.0 HideOrShowTaskbar-anycpu.exe --repo ${{ github.repository }}

  build-x64:
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: x64

    - name: Restore NuGet packages
      run: nuget restore HideOrShowTaskbar.sln  # 替换为您的解决方案文件名

    - name: Build project
      run: |
        msbuild /p:Configuration=Release /p:Platform=x64 HideOrShowTaskbar.csproj

    - name: Create artifacts directory
      run: mkdir artifacts-x64

    - run: Rename-Item -Path "bin\x64\Release\HideOrShowTaskbar.exe" -NewName "HideOrShowTaskbar-x64.exe" -Force

    - run: cd "bin\x64\Release"; gh release upload 1.1.0 HideOrShowTaskbar-x64.exe --repo ${{ github.repository }}
  build-x86:
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: x86

    - name: Restore NuGet packages
      run: nuget restore HideOrShowTaskbar.sln  # 替换为您的解决方案文件名

    - name: Build project
      run: |
        msbuild /p:Configuration=Release /p:Platform=x86 HideOrShowTaskbar.csproj

    - name: Create artifacts directory
      run: mkdir artifacts-x86

    - run: Rename-Item -Path "bin\x86\Release\HideOrShowTaskbar.exe" -NewName "HideOrShowTaskbar-x86.exe" -Force

    - run: cd "bin\x86\Release"; gh release upload 1.1.0 HideOrShowTaskbar-x86.exe --repo ${{ github.repository }}
  build-arm64:
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: arm64

    - name: Restore NuGet packages
      run: nuget restore HideOrShowTaskbar.sln  # 替换为您的解决方案文件名

    - name: Build project
      run: |
        msbuild /p:Configuration=Release /p:Platform=arm64 HideOrShowTaskbar.csproj

    - name: Create artifacts directory
      run: mkdir artifacts-arm64

    - run: Rename-Item -Path "bin\arm64\Release\HideOrShowTaskbar.exe" -NewName "HideOrShowTaskbar-arm64.exe" -Force

    - run: cd "bin\arm64\Release"; gh release upload 1.1.0 HideOrShowTaskbar-arm64.exe --repo ${{ github.repository }}
