name: Multi-Architecture Build

on:
  release:
    types: [published]

jobs:
  build-anycpu:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: anycpu

    - name: Restore NuGet packages
      run: nuget restore HideOrShowTaskbar.sln  # 替换为您的解决方案文件名

    - name: Build project
      run: |
        msbuild /p:Configuration=Release /p:Platform=anycpu HideOrShowTaskbar.csproj

    - name: Create artifacts directory
      run: mkdir artifacts-anycpu

    - name: Copy EXE to artifacts directory
      run: |
        Copy-Item -Path "bin\Release\HideOrShowTaskbar.exe" -Destination "artifacts-anycpu"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: HideOrShowTaskbar-anycpu
        path: artifacts-anycpu\HideOrShowTaskbar.exe
        compression-level: 0
  build-x64:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: x64

    - name: Restore NuGet packages
      run: nuget restore HideOrShowTaskbar.sln  # 替换为您的解决方案文件名

    - name: Build project
      run: |
        msbuild /p:Configuration=Release /p:Platform=x64 HideOrShowTaskbar.csproj

    - name: Create artifacts directory
      run: mkdir artifacts-x64

    - name: Copy EXE to artifacts directory
      run: |
        Copy-Item -Path "bin\Release\HideOrShowTaskbar.exe" -Destination "artifacts-x64"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: HideOrShowTaskbar-x64
        path: artifacts-x64\HideOrShowTaskbar.exe
        compression-level: 0
  build-x86:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: x86

    - name: Restore NuGet packages
      run: nuget restore HideOrShowTaskbar.sln  # 替换为您的解决方案文件名

    - name: Build project
      run: |
        msbuild /p:Configuration=Release /p:Platform=x86 HideOrShowTaskbar.csproj

    - name: Create artifacts directory
      run: mkdir artifacts-x86

    - name: Copy EXE to artifacts directory
      run: |
        Copy-Item -Path "bin\Release\HideOrShowTaskbar.exe" -Destination "artifacts-x86"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: HideOrShowTaskbar-x86
        path: artifacts-x86\HideOrShowTaskbar.exe
        compression-level: 0
  build-arm64:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: arm64

    - name: Restore NuGet packages
      run: nuget restore HideOrShowTaskbar.sln  # 替换为您的解决方案文件名

    - name: Build project
      run: |
        msbuild /p:Configuration=Release /p:Platform=arm64 HideOrShowTaskbar.csproj

    - name: Create artifacts directory
      run: mkdir artifacts-arm64

    - name: Copy EXE to artifacts directory
      run: |
        Copy-Item -Path "bin\Release\HideOrShowTaskbar.exe" -Destination "artifacts-arm64"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: HideOrShowTaskbar-arm64
        path: artifacts-arm64\HideOrShowTaskbar.exe
        compression-level: 0
